use std::sync::mpsc;

use crate::api::auth::{self, AuthResult};
#[cfg(test)]
use crate::api::protocol::APPLICATION_CONTRACT;
use crate::api::protocol::{
    self, AGENT_CONTRACT, ApiError, CallerKind, E_UNSUPPORTED_CAPABILITY, ErrorResponse,
    EvidenceRef, RequestEnvelope, SuccessResponse, TrustedCallerContext,
};

/// A dispatch handler that routes protocol envelopes to CoreRuntime methods.
///
/// The dispatcher is transport-agnostic: it receives a pre-authenticated
/// `TrustedCallerContext` and a `RequestEnvelope`, authorizes the call,
/// and returns a response.
pub struct Dispatcher {
    /// Sender for host events (open_evidence intents).
    #[allow(dead_code)]
    host_event_tx: mpsc::Sender<HostEvent>,
}

/// Events pushed from Core to the authorized Tauri host.
#[derive(Debug, Clone)]
pub enum HostEvent {
    /// A new evidence resolution intent is pending consent.
    PendingOpenEvidence {
        intent_id: String,
        display_metadata: serde_json::Value,
        expires_at: String,
    },
}

impl Dispatcher {
    pub fn new(host_event_tx: mpsc::Sender<HostEvent>) -> Self {
        Self { host_event_tx }
    }

    /// Dispatch a request and return a JSON response.
    ///
    /// The caller context must be generated by the transport/auth adapter
    /// (socket peer credential or in-process Tauri adapter). The payload
    /// must not contain any self-reported caller fields.
    pub fn dispatch(&self, envelope: RequestEnvelope, caller: &TrustedCallerContext) -> String {
        let response = self.dispatch_inner(envelope, caller);
        serde_json::to_string(&response).unwrap_or_else(|_e| {
            serde_json::to_string(&ErrorResponse::new(
                "unknown",
                "",
                ApiError::new("internal_error", "serialization failed", false),
            ))
            .unwrap_or_default()
        })
    }

    fn dispatch_inner(
        &self,
        envelope: RequestEnvelope,
        caller: &TrustedCallerContext,
    ) -> serde_json::Value {
        let contract = &envelope.contract;
        let method = &envelope.method;
        let request_id = &envelope.request_id;

        // Authorize.
        match auth::authorize_method(contract, method, caller) {
            AuthResult::Denied {
                error_code,
                message,
            } => {
                return serde_json::to_value(ErrorResponse::new(
                    contract,
                    request_id,
                    ApiError::new(error_code, message, false),
                ))
                .unwrap();
            }
            AuthResult::Allowed => {}
        }

        // Route to handler.
        match method.as_str() {
            // ── Agent V1 methods ──────────────────────────────────────
            "get_capabilities" => self.handle_get_capabilities(contract, request_id),
            "get_capture_status" => self.handle_get_capture_status(contract, request_id),
            "get_asr_job_status" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "search_transcripts" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "resolve_evidence" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "open_evidence" => self.handle_open_evidence(&envelope, caller, contract, request_id),
            "get_operation" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "list_operations" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }

            // ── Application V1 methods ────────────────────────────────
            "start_capture" => self.handle_start_capture(contract, request_id),
            "stop_capture" => self.handle_stop_capture(contract, request_id),
            "install_model" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "uninstall_model" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "get_model" => self.handle_stub(contract, request_id, method, "not yet implemented"),
            "list_models" => self.handle_stub(contract, request_id, method, "not yet implemented"),
            "import_audio" => self.handle_stub(contract, request_id, method, "not yet implemented"),
            "enqueue_asr_job" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "retry_asr_job" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "cancel_asr_job" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "retranscribe_chunk" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "list_transcript_revisions" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "get_transcript_revision" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "list_provider_receipts" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }

            _ => serde_json::to_value(ErrorResponse::new(
                contract,
                request_id,
                ApiError::unknown_method(method),
            ))
            .unwrap(),
        }
    }

    // ── Implemented handlers ─────────────────────────────────────────────────

    fn handle_get_capabilities(&self, contract: &str, request_id: &str) -> serde_json::Value {
        let caps = protocol::CapabilitiesResponse {
            contract: AGENT_CONTRACT.to_owned(),
            contract_version: protocol::CONTRACT_VERSION,
            capabilities: vec![
                "agent_read".to_owned(),
                "agent_evidence".to_owned(),
                "operation_read".to_owned(),
            ],
            unsupported_capabilities: vec![protocol::UnsupportedCapability {
                capability: "native_capture".to_owned(),
                reason: "native capture requires ScreenCaptureKit + AVAudioEngine milestone"
                    .to_owned(),
                available_at_milestone: Some("native_capture".to_owned()),
            }],
        };
        serde_json::to_value(SuccessResponse::new(
            contract,
            request_id,
            serde_json::to_value(caps).unwrap(),
        ))
        .unwrap()
    }

    fn handle_get_capture_status(&self, contract: &str, request_id: &str) -> serde_json::Value {
        let status = protocol::CaptureStatus {
            active: false,
            capability: "unsupported_capability".to_owned(),
            state: "unsupported".to_owned(),
        };
        serde_json::to_value(SuccessResponse::new(
            contract,
            request_id,
            serde_json::to_value(status).unwrap(),
        ))
        .unwrap()
    }

    fn handle_start_capture(&self, contract: &str, request_id: &str) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::unsupported_capability("native_capture"),
        ))
        .unwrap()
    }

    fn handle_stop_capture(&self, contract: &str, request_id: &str) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::unsupported_capability("native_capture"),
        ))
        .unwrap()
    }

    fn handle_open_evidence(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        // Only Tauri UI can open evidence (via the Host Control flow).
        // Agents receive an EvidenceRef with disposition, and the Tauri host
        // claims/consumes it through the Host Event protocol.
        if caller.kind != CallerKind::TauriUi {
            return serde_json::to_value(ErrorResponse::new(
                contract,
                request_id,
                ApiError::new(
                    E_UNSUPPORTED_CAPABILITY,
                    "open_evidence requires Tauri UI caller",
                    false,
                ),
            ))
            .unwrap();
        }

        // Extract the intent_id from params.
        let intent_id = envelope
            .params
            .get("intent_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if intent_id.is_empty() {
            return serde_json::to_value(ErrorResponse::new(
                contract,
                request_id,
                ApiError::new("invalid_request", "intent_id is required", false),
            ))
            .unwrap();
        }

        // In the full implementation, this would:
        // 1. Look up the intent in open_intent_ledger
        // 2. Verify the caller is the authorized claim_principal
        // 3. Transition intent to consumed/uncertain
        // 4. Return the validated Evidence target
        //
        // For now, return a stub EvidenceRef.
        let evidence = EvidenceRef {
            intent_id: intent_id.to_owned(),
            state: "consumed".to_owned(),
            disposition: "opened".to_owned(),
            expires_at: "2099-01-01T00:00:00Z".to_owned(),
            display_metadata: envelope
                .params
                .get("display_metadata")
                .cloned()
                .unwrap_or_default(),
        };

        serde_json::to_value(SuccessResponse::new(
            contract,
            request_id,
            serde_json::to_value(evidence).unwrap(),
        ))
        .unwrap()
    }

    // ── Stub ──────────────────────────────────────────────────────────────────

    fn handle_stub(
        &self,
        contract: &str,
        request_id: &str,
        method: &str,
        reason: &str,
    ) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::new("not_implemented", reason, false)
                .with_details(serde_json::json!({ "method": method })),
        ))
        .unwrap()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::protocol::CallerKind;

    fn agent_caller() -> TrustedCallerContext {
        TrustedCallerContext {
            principal_id: "agent-1".to_owned(),
            kind: CallerKind::LocalAgent,
            capabilities: vec![
                "agent_read".to_owned(),
                "agent_evidence".to_owned(),
                "operation_read".to_owned(),
            ],
            auth_source: "test".to_owned(),
        }
    }

    fn tauri_caller() -> TrustedCallerContext {
        TrustedCallerContext {
            principal_id: "tauri-1".to_owned(),
            kind: CallerKind::TauriUi,
            capabilities: vec![
                "agent_read".to_owned(),
                "agent_evidence".to_owned(),
                "operation_read".to_owned(),
                "transcript_read".to_owned(),
                "receipt_read".to_owned(),
                "capture_manage".to_owned(),
                "model_manage".to_owned(),
                "import_manage".to_owned(),
                "asr_job_manage".to_owned(),
            ],
            auth_source: "test".to_owned(),
        }
    }

    fn make_envelope(method: &str, params: serde_json::Value) -> RequestEnvelope {
        RequestEnvelope {
            contract: AGENT_CONTRACT.to_owned(),
            contract_version: 1,
            request_id: "req-1".to_owned(),
            method: method.to_owned(),
            params,
        }
    }

    fn make_app_envelope(method: &str, params: serde_json::Value) -> RequestEnvelope {
        RequestEnvelope {
            contract: APPLICATION_CONTRACT.to_owned(),
            contract_version: 1,
            request_id: "req-1".to_owned(),
            method: method.to_owned(),
            params,
        }
    }

    fn parse_response(json: &str) -> serde_json::Value {
        serde_json::from_str(json).unwrap()
    }

    #[test]
    fn agent_get_capabilities() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_envelope("get_capabilities", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert!(
            resp["result"]["capabilities"]
                .as_array()
                .unwrap()
                .contains(&serde_json::json!("agent_read"))
        );
    }

    #[test]
    fn agent_capture_status_returns_unsupported() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_envelope("get_capture_status", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["active"], false);
    }

    #[test]
    fn agent_denied_for_application_only() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_app_envelope("start_capture", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "unsupported_capability");
    }

    #[test]
    fn tauri_start_capture_returns_unsupported() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_app_envelope("start_capture", serde_json::json!({})),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "unsupported_capability");
    }

    #[test]
    fn agent_open_evidence_denied() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_envelope("open_evidence", serde_json::json!({"intent_id": "int-1"})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
    }

    #[test]
    fn tauri_open_evidence_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_app_envelope("open_evidence", serde_json::json!({"intent_id": "int-1"})),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["intent_id"], "int-1");
    }

    #[test]
    fn unknown_method_returns_error() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_envelope("nonexistent_method", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
    }

    #[test]
    fn stub_methods_return_not_implemented() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx);
        let json = d.dispatch(
            make_envelope("search_transcripts", serde_json::json!({"query": "test"})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "not_implemented");
    }
}
