use std::hash::{Hash, Hasher};
use std::sync::mpsc;

use crate::api::auth::{self, AuthResult};
use crate::api::cursor::Cursor;
use crate::api::idempotency::{self, IdempotencyResult};
#[cfg(test)]
use crate::api::protocol::APPLICATION_CONTRACT;
use crate::api::protocol::{
    self, AGENT_CONTRACT, ApiError, AsrJobSummary, CallerKind, E_INTERNAL, E_INVALID_REQUEST,
    E_OPERATION_IN_PROGRESS, E_UNSUPPORTED_CAPABILITY, ErrorResponse, EvidenceRef, ModelSummary,
    OperationSummary, RequestEnvelope, SuccessResponse, TranscriptSegmentSummary,
    TrustedCallerContext,
};
use crate::catalog::Catalog;

/// A dispatch handler that routes protocol envelopes to CoreRuntime methods.
///
/// The dispatcher is transport-agnostic: it receives a pre-authenticated
/// `TrustedCallerContext` and a `RequestEnvelope`, authorizes the call,
/// and returns a response.
pub struct Dispatcher {
    /// Sender for host events (open_evidence intents).
    #[allow(dead_code)]
    host_event_tx: mpsc::Sender<HostEvent>,
    /// Catalog for read queries and idempotency.
    catalog: Catalog,
}

/// Events pushed from Core to the authorized Tauri host.
#[derive(Debug, Clone)]
pub enum HostEvent {
    /// A new evidence resolution intent is pending consent.
    PendingOpenEvidence {
        intent_id: String,
        display_metadata: serde_json::Value,
        expires_at: String,
    },
}

impl Dispatcher {
    pub fn new(host_event_tx: mpsc::Sender<HostEvent>, catalog: Catalog) -> Self {
        Self {
            host_event_tx,
            catalog,
        }
    }

    /// Dispatch a request and return a JSON response.
    ///
    /// The caller context must be generated by the transport/auth adapter
    /// (socket peer credential or in-process Tauri adapter). The payload
    /// must not contain any self-reported caller fields.
    pub fn dispatch(&self, envelope: RequestEnvelope, caller: &TrustedCallerContext) -> String {
        let response = self.dispatch_inner(envelope, caller);
        serde_json::to_string(&response).unwrap_or_else(|_e| {
            serde_json::to_string(&ErrorResponse::new(
                "unknown",
                "",
                ApiError::new("internal_error", "serialization failed", false),
            ))
            .unwrap_or_default()
        })
    }

    fn dispatch_inner(
        &self,
        envelope: RequestEnvelope,
        caller: &TrustedCallerContext,
    ) -> serde_json::Value {
        let contract = &envelope.contract;
        let method = &envelope.method;
        let request_id = &envelope.request_id;

        // Authorize.
        match auth::authorize_method(contract, method, caller) {
            AuthResult::Denied {
                error_code,
                message,
            } => {
                return serde_json::to_value(ErrorResponse::new(
                    contract,
                    request_id,
                    ApiError::new(error_code, message, false),
                ))
                .unwrap();
            }
            AuthResult::Allowed => {}
        }

        // Route to handler.
        match method.as_str() {
            // ── Agent V1 methods ──────────────────────────────────────
            "get_capabilities" => self.handle_get_capabilities(contract, request_id),
            "get_capture_status" => self.handle_get_capture_status(contract, request_id),
            "get_asr_job_status" => self.handle_get_asr_job_status(&envelope, contract, request_id),
            "search_transcripts" => {
                self.handle_search_transcripts(&envelope, caller, contract, request_id)
            }
            "resolve_evidence" => {
                self.handle_resolve_evidence(&envelope, caller, contract, request_id)
            }
            "open_evidence" => self.handle_open_evidence(&envelope, caller, contract, request_id),
            "get_operation" => self.handle_get_operation(&envelope, contract, request_id),
            "list_operations" => {
                self.handle_list_operations(&envelope, caller, contract, request_id)
            }

            // ── Application V1 methods ────────────────────────────────
            "start_capture" => self.handle_start_capture(contract, request_id),
            "stop_capture" => self.handle_stop_capture(contract, request_id),
            "install_model" => self.handle_install_model(&envelope, caller, contract, request_id),
            "uninstall_model" => {
                self.handle_uninstall_model(&envelope, caller, contract, request_id)
            }
            "get_model" => self.handle_get_model(&envelope, contract, request_id),
            "list_models" => self.handle_list_models(contract, request_id),
            "import_audio" => self.handle_import_audio(&envelope, caller, contract, request_id),
            "enqueue_asr_job" => {
                self.handle_enqueue_asr_job(&envelope, caller, contract, request_id)
            }
            "retry_asr_job" => self.handle_retry_asr_job(&envelope, caller, contract, request_id),
            "cancel_asr_job" => self.handle_cancel_asr_job(&envelope, caller, contract, request_id),
            "retranscribe_chunk" => {
                self.handle_retranscribe_chunk(&envelope, caller, contract, request_id)
            }
            "list_transcript_revisions" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "get_transcript_revision" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }
            "list_provider_receipts" => {
                self.handle_stub(contract, request_id, method, "not yet implemented")
            }

            _ => serde_json::to_value(ErrorResponse::new(
                contract,
                request_id,
                ApiError::unknown_method(method),
            ))
            .unwrap(),
        }
    }

    // ── Implemented handlers ─────────────────────────────────────────────────

    fn handle_get_capabilities(&self, contract: &str, request_id: &str) -> serde_json::Value {
        let caps = protocol::CapabilitiesResponse {
            contract: AGENT_CONTRACT.to_owned(),
            contract_version: protocol::CONTRACT_VERSION,
            capabilities: vec![
                "agent_read".to_owned(),
                "agent_evidence".to_owned(),
                "operation_read".to_owned(),
            ],
            unsupported_capabilities: vec![protocol::UnsupportedCapability {
                capability: "native_capture".to_owned(),
                reason: "native capture requires ScreenCaptureKit + AVAudioEngine milestone"
                    .to_owned(),
                available_at_milestone: Some("native_capture".to_owned()),
            }],
        };
        serde_json::to_value(SuccessResponse::new(
            contract,
            request_id,
            serde_json::to_value(caps).unwrap(),
        ))
        .unwrap()
    }

    fn handle_get_capture_status(&self, contract: &str, request_id: &str) -> serde_json::Value {
        let status = protocol::CaptureStatus {
            active: false,
            capability: "unsupported_capability".to_owned(),
            state: "unsupported".to_owned(),
        };
        serde_json::to_value(SuccessResponse::new(
            contract,
            request_id,
            serde_json::to_value(status).unwrap(),
        ))
        .unwrap()
    }

    fn handle_start_capture(&self, contract: &str, request_id: &str) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::unsupported_capability("native_capture"),
        ))
        .unwrap()
    }

    fn handle_stop_capture(&self, contract: &str, request_id: &str) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::unsupported_capability("native_capture"),
        ))
        .unwrap()
    }

    fn handle_open_evidence(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        // Only Tauri UI can open evidence (via the Host Control flow).
        // Agents receive an EvidenceRef with disposition, and the Tauri host
        // claims/consumes it through the Host Event protocol.
        if caller.kind != CallerKind::TauriUi {
            return serde_json::to_value(ErrorResponse::new(
                contract,
                request_id,
                ApiError::new(
                    E_UNSUPPORTED_CAPABILITY,
                    "open_evidence requires Tauri UI caller",
                    false,
                ),
            ))
            .unwrap();
        }

        // Extract the intent_id from params.
        let intent_id = envelope
            .params
            .get("intent_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if intent_id.is_empty() {
            return serde_json::to_value(ErrorResponse::new(
                contract,
                request_id,
                ApiError::new("invalid_request", "intent_id is required", false),
            ))
            .unwrap();
        }

        // In the full implementation, this would:
        // 1. Look up the intent in open_intent_ledger
        // 2. Verify the caller is the authorized claim_principal
        // 3. Transition intent to consumed/uncertain
        // 4. Return the validated Evidence target
        //
        // For now, return a stub EvidenceRef.
        let evidence = EvidenceRef {
            intent_id: intent_id.to_owned(),
            state: "consumed".to_owned(),
            disposition: "opened".to_owned(),
            expires_at: "2099-01-01T00:00:00Z".to_owned(),
            display_metadata: envelope
                .params
                .get("display_metadata")
                .cloned()
                .unwrap_or_default(),
        };

        serde_json::to_value(SuccessResponse::new(
            contract,
            request_id,
            serde_json::to_value(evidence).unwrap(),
        ))
        .unwrap()
    }

    // ── Read handlers (query methods) ─────────────────────────────────────────

    fn handle_get_asr_job_status(
        &self,
        envelope: &RequestEnvelope,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let job_id = envelope
            .params
            .get("job_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if job_id.is_empty() {
            return self.error_response(
                contract,
                request_id,
                "invalid_request",
                "job_id is required",
            );
        }

        let conn = self.catalog.connection();
        let job: rusqlite::Result<AsrJobSummary> = conn.query_row(
            "SELECT id, session_id, chunk_id, provider, model_id, state, attempt_count,
                    error_code, created_at, updated_at
             FROM asr_jobs WHERE id = ?1",
            [job_id],
            |row| {
                Ok(AsrJobSummary {
                    id: row.get(0)?,
                    session_id: row.get(1)?,
                    chunk_id: row.get(2)?,
                    provider: row.get(3)?,
                    model_id: row.get(4)?,
                    state: row.get(5)?,
                    attempt_count: row.get(6)?,
                    error_code: row.get(7)?,
                    created_at: row.get(8)?,
                    updated_at: row.get(9)?,
                })
            },
        );
        drop(conn);

        match job {
            Ok(summary) => serde_json::to_value(SuccessResponse::new(
                contract,
                request_id,
                serde_json::to_value(summary).unwrap(),
            ))
            .unwrap(),
            Err(_) => self.error_response(contract, request_id, "job_not_found", "job not found"),
        }
    }

    fn handle_search_transcripts(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let query = envelope
            .params
            .get("query")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if query.is_empty() {
            return self.error_response(
                contract,
                request_id,
                "invalid_request",
                "query is required",
            );
        }
        let limit = envelope
            .params
            .get("limit")
            .and_then(|v| v.as_u64())
            .unwrap_or(20) as u32;
        let limit = limit.clamp(1, 50);

        // Decode cursor if present.
        let mut last_keyset: Option<serde_json::Value> = None;
        if let Some(cursor_str) = envelope.params.get("cursor").and_then(|v| v.as_str()) {
            match Cursor::decode(
                cursor_str,
                contract,
                "search_transcripts",
                &caller.principal_id,
                &self.catalog,
            ) {
                Ok(cursor) => last_keyset = cursor.last_keyset,
                Err(_) => {
                    return self.error_response(
                        contract,
                        request_id,
                        "invalid_cursor",
                        "invalid cursor",
                    );
                }
            }
        }

        let segments = self.catalog.search_segments(query);
        match segments {
            Ok(mut results) => {
                // Apply keyset pagination if we have a cursor.
                if let Some(ref keyset) = last_keyset {
                    let _ = keyset;
                    // Simple truncation-based pagination for now.
                    results.truncate(limit as usize);
                } else {
                    results.truncate(limit as usize);
                }

                let summaries: Vec<TranscriptSegmentSummary> = results
                    .into_iter()
                    .map(|s| TranscriptSegmentSummary {
                        segment_id: s.id,
                        revision_id: String::new(),
                        start_ms: s.start_ms,
                        end_ms: s.end_ms,
                        text: s.text,
                    })
                    .collect();

                let next_cursor = if summaries.len() == limit as usize {
                    Some(
                        Cursor::new(
                            contract,
                            "search_transcripts",
                            &caller.principal_id,
                            limit,
                            &self.catalog,
                            300,
                        )
                        .encode(),
                    )
                } else {
                    None
                };

                let response = protocol::PaginatedResponse {
                    items: summaries,
                    next_cursor,
                };
                serde_json::to_value(SuccessResponse::new(
                    contract,
                    request_id,
                    serde_json::to_value(response).unwrap(),
                ))
                .unwrap()
            }
            Err(_) => self.error_response(contract, request_id, "internal_error", "search failed"),
        }
    }

    fn handle_get_model(
        &self,
        envelope: &RequestEnvelope,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let model_id = envelope
            .params
            .get("model_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if model_id.is_empty() {
            return self.error_response(
                contract,
                request_id,
                "invalid_request",
                "model_id is required",
            );
        }

        let conn = self.catalog.connection();
        let model: rusqlite::Result<ModelSummary> = conn.query_row(
            "SELECT model_id, provider, manifest_version, state, installed_at, qualified_at
             FROM model_installations WHERE model_id = ?1",
            [model_id],
            |row| {
                Ok(ModelSummary {
                    model_id: row.get(0)?,
                    provider: row.get(1)?,
                    manifest_version: row.get(2)?,
                    state: row.get(3)?,
                    installed_at: row.get(4)?,
                    qualified_at: row.get(5)?,
                })
            },
        );
        drop(conn);

        match model {
            Ok(summary) => serde_json::to_value(SuccessResponse::new(
                contract,
                request_id,
                serde_json::to_value(summary).unwrap(),
            ))
            .unwrap(),
            Err(_) => {
                self.error_response(contract, request_id, "model_not_found", "model not found")
            }
        }
    }

    fn handle_list_models(&self, contract: &str, request_id: &str) -> serde_json::Value {
        let conn = self.catalog.connection();
        let models: rusqlite::Result<Vec<ModelSummary>> = {
            let mut stmt = conn
                .prepare(
                    "SELECT model_id, provider, manifest_version, state, installed_at, qualified_at
                     FROM model_installations
                     ORDER BY provider ASC, model_id ASC",
                )
                .unwrap();
            let rows = stmt
                .query_map([], |row| {
                    Ok(ModelSummary {
                        model_id: row.get(0)?,
                        provider: row.get(1)?,
                        manifest_version: row.get(2)?,
                        state: row.get(3)?,
                        installed_at: row.get(4)?,
                        qualified_at: row.get(5)?,
                    })
                })
                .unwrap();
            rows.collect()
        };
        drop(conn);

        match models {
            Ok(list) => serde_json::to_value(SuccessResponse::new(
                contract,
                request_id,
                serde_json::to_value(list).unwrap(),
            ))
            .unwrap(),
            Err(_) => self.error_response(contract, request_id, "internal_error", "list failed"),
        }
    }

    fn handle_get_operation(
        &self,
        envelope: &RequestEnvelope,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let operation_id = envelope
            .params
            .get("operation_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        if operation_id.is_empty() {
            return self.error_response(
                contract,
                request_id,
                "invalid_request",
                "operation_id is required",
            );
        }

        let conn = self.catalog.connection();
        let op: rusqlite::Result<OperationSummary> = conn.query_row(
            "SELECT id, kind, state, method, created_at, updated_at, last_error_code, last_error_summary
             FROM operations WHERE id = ?1",
            [operation_id],
            |row| {
                Ok(OperationSummary {
                    id: row.get(0)?,
                    kind: row.get(1)?,
                    state: row.get(2)?,
                    method: row.get(3)?,
                    created_at: row.get(4)?,
                    updated_at: row.get(5)?,
                    last_error_code: row.get(6)?,
                    last_error_summary: row.get(7)?,
                })
            },
        );
        drop(conn);

        match op {
            Ok(summary) => serde_json::to_value(SuccessResponse::new(
                contract,
                request_id,
                serde_json::to_value(summary).unwrap(),
            ))
            .unwrap(),
            Err(_) => self.error_response(
                contract,
                request_id,
                "operation_not_found",
                "operation not found",
            ),
        }
    }

    fn handle_list_operations(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let limit = envelope
            .params
            .get("limit")
            .and_then(|v| v.as_u64())
            .unwrap_or(20) as u32;
        let limit = limit.clamp(1, 50);

        let conn = self.catalog.connection();
        let ops: rusqlite::Result<Vec<OperationSummary>> = {
            let mut stmt = conn
                .prepare(
                    "SELECT id, kind, state, method, created_at, updated_at, last_error_code, last_error_summary
                     FROM operations
                     WHERE principal_id = ?1
                     ORDER BY created_at DESC, id ASC
                     LIMIT ?2",
                )
                .unwrap();
            let rows = stmt
                .query_map(rusqlite::params![caller.principal_id, limit], |row| {
                    Ok(OperationSummary {
                        id: row.get(0)?,
                        kind: row.get(1)?,
                        state: row.get(2)?,
                        method: row.get(3)?,
                        created_at: row.get(4)?,
                        updated_at: row.get(5)?,
                        last_error_code: row.get(6)?,
                        last_error_summary: row.get(7)?,
                    })
                })
                .unwrap();
            rows.collect()
        };
        drop(conn);

        match ops {
            Ok(list) => serde_json::to_value(SuccessResponse::new(
                contract,
                request_id,
                serde_json::to_value(list).unwrap(),
            ))
            .unwrap(),
            Err(_) => self.error_response(contract, request_id, "internal_error", "list failed"),
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    fn error_response(
        &self,
        contract: &str,
        request_id: &str,
        code: &str,
        message: &str,
    ) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::new(code, message, false),
        ))
        .unwrap()
    }

    // ── Stub ──────────────────────────────────────────────────────────────────

    fn handle_stub(
        &self,
        contract: &str,
        request_id: &str,
        method: &str,
        reason: &str,
    ) -> serde_json::Value {
        serde_json::to_value(ErrorResponse::new(
            contract,
            request_id,
            ApiError::new("not_implemented", reason, false)
                .with_details(serde_json::json!({ "method": method })),
        ))
        .unwrap()
    }

    // ── Mutation helpers ──────────────────────────────────────────────────────

    /// Hash envelope params to a stable fingerprint for idempotency.
    fn hash_params(params: &serde_json::Value) -> String {
        let mut hasher = std::collections::hash_map::DefaultHasher::new();
        params.to_string().hash(&mut hasher);
        format!("{:x}", hasher.finish())
    }

    /// Create a new operation row and return its summary.
    fn create_operation(
        catalog: &Catalog,
        kind: &str,
        method: &str,
        principal_id: &str,
        principal_kind: &str,
    ) -> Result<OperationSummary, rusqlite::Error> {
        let id = format!("op_{}", uuid::Uuid::new_v4().simple());
        let now = chrono::Utc::now().to_rfc3339();
        catalog.connection().execute(
            "INSERT INTO operations (id, kind, state, principal_id, principal_kind, method, created_at, updated_at)
             VALUES (?1, ?2, 'queued', ?3, ?4, ?5, ?6, ?6)",
            rusqlite::params![id, kind, principal_id, principal_kind, method, now],
        )?;
        Ok(OperationSummary {
            id,
            kind: kind.to_owned(),
            state: "queued".to_owned(),
            method: method.to_owned(),
            created_at: now.clone(),
            updated_at: now,
            last_error_code: None,
            last_error_summary: None,
        })
    }

    /// Commit or roll back an idempotency key after business logic runs.
    fn finalize_mutation(
        &self,
        contract: &str,
        contract_version: u32,
        request_id: &str,
        caller: &TrustedCallerContext,
        idempotency_key: &str,
        result: Result<serde_json::Value, (String, String)>,
    ) -> serde_json::Value {
        match result {
            Ok(value) => {
                let response = SuccessResponse::new(contract, request_id, value);
                let response_json = serde_json::to_string(&response).unwrap_or_default();
                let _ = idempotency::commit_success(
                    &self.catalog,
                    contract,
                    contract_version,
                    &caller.principal_id,
                    idempotency_key,
                    &response_json,
                    None,
                );
                serde_json::to_value(response).unwrap()
            }
            Err((code, message)) => {
                let _ = idempotency::commit_failure(
                    &self.catalog,
                    contract,
                    contract_version,
                    &caller.principal_id,
                    idempotency_key,
                    &code,
                    &message,
                );
                self.error_response(contract, request_id, &code, &message)
            }
        }
    }

    /// Run the full idempotency-guarded mutation flow.
    ///
    /// Checks or claims the idempotency key, then calls `on_proceed` for
    /// new requests, and wraps the result through `finalize_mutation`.
    #[allow(clippy::too_many_arguments)]
    fn mutation_flow(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
        method: &str,
        idempotency_key: &str,
        on_proceed: impl FnOnce() -> Result<serde_json::Value, (String, String)>,
    ) -> serde_json::Value {
        let fingerprint = Self::hash_params(&envelope.params);

        match idempotency::check_or_claim(
            &self.catalog,
            contract,
            envelope.contract_version,
            caller,
            method,
            idempotency_key,
            &fingerprint,
        ) {
            Ok(IdempotencyResult::Proceed) => {
                let result = on_proceed();
                self.finalize_mutation(
                    contract,
                    envelope.contract_version,
                    request_id,
                    caller,
                    idempotency_key,
                    result,
                )
            }
            Ok(IdempotencyResult::InProgress { operation_id }) => self.error_response(
                contract,
                request_id,
                E_OPERATION_IN_PROGRESS,
                &format!("operation {} is in progress", operation_id),
            ),
            Ok(IdempotencyResult::Succeeded { response_json }) => {
                serde_json::from_str(&response_json).unwrap_or_else(|_| {
                    self.error_response(
                        contract,
                        request_id,
                        E_INTERNAL,
                        "cached response corrupted",
                    )
                })
            }
            Ok(IdempotencyResult::Failed {
                error_code,
                error_message_key,
            }) => self.error_response(contract, request_id, &error_code, &error_message_key),
            Err(_) => {
                self.error_response(contract, request_id, E_INTERNAL, "idempotency check failed")
            }
        }
    }

    // ── Mutation handlers ─────────────────────────────────────────────────────

    fn handle_install_model(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "install_model";
        let model_id = envelope
            .params
            .get("model_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if model_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "model_id and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "model_download",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_uninstall_model(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "uninstall_model";
        let model_id = envelope
            .params
            .get("model_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if model_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "model_id and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "model_delete",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_import_audio(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "import_audio";
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "idempotency_key is required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "import_audio",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_enqueue_asr_job(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "enqueue_asr_job";
        let chunk_id = envelope
            .params
            .get("chunk_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let model_id = envelope
            .params
            .get("model_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if chunk_id.is_empty() || model_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "chunk_id, model_id, and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "asr_job",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_retry_asr_job(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "retry_asr_job";
        let job_id = envelope
            .params
            .get("job_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if job_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "job_id and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "asr_retry",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_cancel_asr_job(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "cancel_asr_job";
        let job_id = envelope
            .params
            .get("job_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if job_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "job_id and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "asr_cancel",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_retranscribe_chunk(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "retranscribe_chunk";
        let chunk_id = envelope
            .params
            .get("chunk_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let model_id = envelope
            .params
            .get("model_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if chunk_id.is_empty() || model_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "chunk_id, model_id, and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || match Self::create_operation(
                &self.catalog,
                "retranscribe",
                method,
                &caller.principal_id,
                &caller.kind.to_string(),
            ) {
                Ok(op) => Ok(serde_json::to_value(op).unwrap()),
                Err(e) => Err((
                    E_INTERNAL.to_owned(),
                    format!("failed to create operation: {e}"),
                )),
            },
        )
    }

    fn handle_resolve_evidence(
        &self,
        envelope: &RequestEnvelope,
        caller: &TrustedCallerContext,
        contract: &str,
        request_id: &str,
    ) -> serde_json::Value {
        let method = "resolve_evidence";
        let intent_id = envelope
            .params
            .get("intent_id")
            .and_then(|v| v.as_str())
            .unwrap_or("");
        let idempotency_key = envelope
            .params
            .get("idempotency_key")
            .and_then(|v| v.as_str())
            .unwrap_or("");

        if intent_id.is_empty() || idempotency_key.is_empty() {
            return self.error_response(
                contract,
                request_id,
                E_INVALID_REQUEST,
                "intent_id and idempotency_key are required",
            );
        }

        self.mutation_flow(
            envelope,
            caller,
            contract,
            request_id,
            method,
            idempotency_key,
            || {
                let evidence = EvidenceRef {
                    intent_id: intent_id.to_owned(),
                    state: "pending".to_owned(),
                    disposition: "requires_consent".to_owned(),
                    expires_at: "2099-01-01T00:00:00Z".to_owned(),
                    display_metadata: envelope
                        .params
                        .get("display_metadata")
                        .cloned()
                        .unwrap_or_default(),
                };
                Ok(serde_json::to_value(evidence).unwrap())
            },
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::api::protocol::CallerKind;

    fn agent_caller() -> TrustedCallerContext {
        TrustedCallerContext {
            principal_id: "agent-1".to_owned(),
            kind: CallerKind::LocalAgent,
            capabilities: vec![
                "agent_read".to_owned(),
                "agent_evidence".to_owned(),
                "operation_read".to_owned(),
            ],
            auth_source: "test".to_owned(),
        }
    }

    fn tauri_caller() -> TrustedCallerContext {
        TrustedCallerContext {
            principal_id: "tauri-1".to_owned(),
            kind: CallerKind::TauriUi,
            capabilities: vec![
                "agent_read".to_owned(),
                "agent_evidence".to_owned(),
                "operation_read".to_owned(),
                "transcript_read".to_owned(),
                "receipt_read".to_owned(),
                "capture_manage".to_owned(),
                "model_manage".to_owned(),
                "import_manage".to_owned(),
                "asr_job_manage".to_owned(),
            ],
            auth_source: "test".to_owned(),
        }
    }

    fn make_envelope(method: &str, params: serde_json::Value) -> RequestEnvelope {
        RequestEnvelope {
            contract: AGENT_CONTRACT.to_owned(),
            contract_version: 1,
            request_id: "req-1".to_owned(),
            method: method.to_owned(),
            params,
        }
    }

    fn make_app_envelope(method: &str, params: serde_json::Value) -> RequestEnvelope {
        RequestEnvelope {
            contract: APPLICATION_CONTRACT.to_owned(),
            contract_version: 1,
            request_id: "req-1".to_owned(),
            method: method.to_owned(),
            params,
        }
    }

    fn parse_response(json: &str) -> serde_json::Value {
        serde_json::from_str(json).unwrap()
    }

    fn test_catalog() -> Catalog {
        let mut catalog = Catalog::in_memory().unwrap();
        crate::catalog::migrations::migrate(catalog.connection_mut()).unwrap();
        catalog
    }

    #[test]
    fn agent_get_capabilities() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope("get_capabilities", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert!(
            resp["result"]["capabilities"]
                .as_array()
                .unwrap()
                .contains(&serde_json::json!("agent_read"))
        );
    }

    #[test]
    fn agent_capture_status_returns_unsupported() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope("get_capture_status", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["active"], false);
    }

    #[test]
    fn agent_denied_for_application_only() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope("start_capture", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "unsupported_capability");
    }

    #[test]
    fn tauri_start_capture_returns_unsupported() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope("start_capture", serde_json::json!({})),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "unsupported_capability");
    }

    #[test]
    fn agent_open_evidence_denied() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope("open_evidence", serde_json::json!({"intent_id": "int-1"})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
    }

    #[test]
    fn tauri_open_evidence_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope("open_evidence", serde_json::json!({"intent_id": "int-1"})),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["intent_id"], "int-1");
    }

    #[test]
    fn unknown_method_returns_error() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope("nonexistent_method", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
    }

    #[test]
    fn stub_methods_return_not_implemented() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "list_transcript_revisions",
                serde_json::json!({"session_id": "x"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "not_implemented");
    }

    #[test]
    fn search_transcripts_returns_empty_results() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope("search_transcripts", serde_json::json!({"query": "test"})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert!(resp["result"]["items"].as_array().unwrap().is_empty());
    }

    #[test]
    fn list_models_returns_empty() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope("list_models", serde_json::json!({})),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert!(resp["result"].as_array().unwrap().is_empty());
    }

    #[test]
    fn get_model_returns_not_found() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope("get_model", serde_json::json!({"model_id": "nonexistent"})),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "model_not_found");
    }

    #[test]
    fn get_asr_job_returns_not_found() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope(
                "get_asr_job_status",
                serde_json::json!({"job_id": "nonexistent"}),
            ),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "job_not_found");
    }

    #[test]
    fn list_operations_returns_empty() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope("list_operations", serde_json::json!({})),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert!(resp["result"].as_array().unwrap().is_empty());
    }

    #[test]
    fn get_operation_returns_not_found() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope(
                "get_operation",
                serde_json::json!({"operation_id": "nonexistent"}),
            ),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "operation_not_found");
    }

    // ── Mutation tests ────────────────────────────────────────────────────────

    #[test]
    fn install_model_succeeds_with_idempotency() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "install_model",
                serde_json::json!({"model_id": "whisper-tiny", "idempotency_key": "ik-1"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "model_download");
        assert_eq!(resp["result"]["state"], "queued");
        assert!(resp["result"]["id"].as_str().unwrap().starts_with("op_"));
    }

    #[test]
    fn install_model_duplicate_idempotency_returns_cached_success() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let params = serde_json::json!({"model_id": "whisper-tiny", "idempotency_key": "ik-2"});

        let json1 = d.dispatch(
            make_app_envelope("install_model", params.clone()),
            &tauri_caller(),
        );
        assert_eq!(parse_response(&json1)["ok"], true);

        let json2 = d.dispatch(make_app_envelope("install_model", params), &tauri_caller());
        let resp = parse_response(&json2);
        // After commit_success, the cached result is Succeeded.
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "model_download");
    }

    #[test]
    fn install_model_requires_model_id() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "install_model",
                serde_json::json!({"idempotency_key": "ik-3"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "invalid_request");
    }

    #[test]
    fn install_model_agent_denied() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "install_model",
                serde_json::json!({"model_id": "m", "idempotency_key": "ik-4"}),
            ),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "unsupported_capability");
    }

    #[test]
    fn uninstall_model_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "uninstall_model",
                serde_json::json!({"model_id": "whisper-tiny", "idempotency_key": "ik-5"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "model_delete");
    }

    #[test]
    fn import_audio_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "import_audio",
                serde_json::json!({"idempotency_key": "ik-6"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "import_audio");
        assert_eq!(resp["result"]["state"], "queued");
    }

    #[test]
    fn enqueue_asr_job_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "enqueue_asr_job",
                serde_json::json!({
                    "chunk_id": "ch-1",
                    "model_id": "whisper-tiny",
                    "idempotency_key": "ik-7"
                }),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "asr_job");
    }

    #[test]
    fn enqueue_asr_job_requires_chunk_id() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "enqueue_asr_job",
                serde_json::json!({"model_id": "m", "idempotency_key": "ik-8"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "invalid_request");
    }

    #[test]
    fn retry_asr_job_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "retry_asr_job",
                serde_json::json!({"job_id": "job-1", "idempotency_key": "ik-9"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "asr_retry");
    }

    #[test]
    fn cancel_asr_job_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "cancel_asr_job",
                serde_json::json!({"job_id": "job-1", "idempotency_key": "ik-10"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "asr_cancel");
    }

    #[test]
    fn retranscribe_chunk_succeeds() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_app_envelope(
                "retranscribe_chunk",
                serde_json::json!({
                    "chunk_id": "ch-1",
                    "model_id": "whisper-tiny",
                    "idempotency_key": "ik-11"
                }),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "retranscribe");
    }

    #[test]
    fn resolve_evidence_succeeds_for_agent() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope(
                "resolve_evidence",
                serde_json::json!({"intent_id": "int-1", "idempotency_key": "ik-12"}),
            ),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["intent_id"], "int-1");
        assert_eq!(resp["result"]["disposition"], "requires_consent");
    }

    #[test]
    fn resolve_evidence_requires_intent_id() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let json = d.dispatch(
            make_envelope(
                "resolve_evidence",
                serde_json::json!({"idempotency_key": "ik-13"}),
            ),
            &agent_caller(),
        );
        let resp = parse_response(&json);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "invalid_request");
    }

    #[test]
    fn mutation_idempotency_caches_success() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let params = serde_json::json!({"model_id": "m", "idempotency_key": "ik-14"});

        // First call succeeds.
        let json1 = d.dispatch(
            make_app_envelope("install_model", params.clone()),
            &tauri_caller(),
        );
        assert_eq!(parse_response(&json1)["ok"], true);

        // Second call returns cached in_progress (since we never committed success).
        // Wait, actually the first call committed success via finalize_mutation.
        // Let me verify: after first call, the idempotency key is in "succeeded" state.
        // So the second call should return the cached success.
        let json2 = d.dispatch(make_app_envelope("install_model", params), &tauri_caller());
        let resp = parse_response(&json2);
        // Since the first call finished and committed success, the second call
        // should see the cached result (Succeeded) and return it.
        assert_eq!(resp["ok"], true);
        assert_eq!(resp["result"]["kind"], "model_download");
    }

    #[test]
    fn mutation_idempotency_different_principals_independent() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());
        let params = serde_json::json!({"model_id": "m", "idempotency_key": "ik-15"});

        // Tauri caller succeeds.
        let json1 = d.dispatch(
            make_app_envelope("install_model", params.clone()),
            &tauri_caller(),
        );
        assert_eq!(parse_response(&json1)["ok"], true);

        // Agent caller is denied by auth (not by idempotency).
        let json2 = d.dispatch(make_app_envelope("install_model", params), &agent_caller());
        let resp = parse_response(&json2);
        assert_eq!(resp["ok"], false);
        assert_eq!(resp["error"]["code"], "unsupported_capability");
    }

    #[test]
    fn mutation_idempotency_different_contracts_independent() {
        let (tx, _rx) = mpsc::channel();
        let d = Dispatcher::new(tx, test_catalog());

        // Agent contract resolve_evidence with key "ik-16".
        let json1 = d.dispatch(
            make_envelope(
                "resolve_evidence",
                serde_json::json!({"intent_id": "int-1", "idempotency_key": "ik-16"}),
            ),
            &agent_caller(),
        );
        assert_eq!(parse_response(&json1)["ok"], true);

        // Application contract install_model with same key "ik-16" — different
        // contract, so should proceed independently.
        let json2 = d.dispatch(
            make_app_envelope(
                "install_model",
                serde_json::json!({"model_id": "m", "idempotency_key": "ik-16"}),
            ),
            &tauri_caller(),
        );
        assert_eq!(parse_response(&json2)["ok"], true);
    }

    #[test]
    fn operation_is_persisted_in_db() {
        let (tx, _rx) = mpsc::channel();
        let catalog = test_catalog();
        let d = Dispatcher::new(tx, catalog);

        let json = d.dispatch(
            make_app_envelope(
                "install_model",
                serde_json::json!({"model_id": "m", "idempotency_key": "ik-17"}),
            ),
            &tauri_caller(),
        );
        let resp = parse_response(&json);
        let op_id = resp["result"]["id"].as_str().unwrap().to_owned();

        // Verify operation exists in the database.
        let conn = d.catalog.connection();
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM operations WHERE id = ?1",
                [&op_id],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(count, 1);
    }

    #[test]
    fn tool_request_is_persisted_in_db() {
        let (tx, _rx) = mpsc::channel();
        let catalog = test_catalog();
        let d = Dispatcher::new(tx, catalog);

        let _json = d.dispatch(
            make_app_envelope(
                "install_model",
                serde_json::json!({"model_id": "m", "idempotency_key": "ik-18"}),
            ),
            &tauri_caller(),
        );

        let conn = d.catalog.connection();
        let state: String = conn
            .query_row(
                "SELECT state FROM tool_requests WHERE idempotency_key = 'ik-18'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        assert_eq!(state, "succeeded");
    }

    #[test]
    fn mutation_failure_commits_error_state() {
        let (tx, _rx) = mpsc::channel();
        let catalog = test_catalog();
        let d = Dispatcher::new(tx, catalog);

        // This call will fail because idempotency_key is missing.
        let _json = d.dispatch(
            make_app_envelope("install_model", serde_json::json!({"model_id": "m"})),
            &tauri_caller(),
        );

        // No tool_request row should be created since validation failed
        // before the idempotency check.
        let conn = d.catalog.connection();
        let count: i64 = conn
            .query_row(
                "SELECT COUNT(*) FROM tool_requests WHERE method = 'install_model'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        // Only the rows from other tests might exist; this one was rejected early.
        // The key point is that this specific request created no row.
        assert_eq!(count, 0);
    }
}
